# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-16 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_card_number', models.CharField(max_length=50)),
                ('cvv', models.CharField(max_length=50)),
                ('expiry_details', models.CharField(max_length=50)),
                ('post_code', models.CharField(max_length=50)),
            ],
        ),
    ]
