# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-16 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_delete_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='order',
        ),
    ]
