# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-16 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_remove_orderlineitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.Order'),
        ),
    ]
