# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-23 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20200223_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
