# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-03 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0247_remove_product_image'),
        ('checkout', '0012_auto_20200223_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
