# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-04 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_remove_order_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.Order')),
                ('purchases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.OrderLineItem')),
            ],
        ),
    ]
