# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-04 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0015_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='purchases',
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
