# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-05 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0017_orderlineitem_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='total',
        ),
    ]
