# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-05 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0019_auto_20200305_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
