# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-05 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0021_orderlineitem_big_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='big_total',
            field=models.FloatField(),
        ),
    ]
