# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-06 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0023_auto_20200306_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='sub_total',
            field=models.FloatField(blank=True),
        ),
    ]
