# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-06 00:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0025_auto_20200306_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='sub_total',
            new_name='big_total',
        ),
    ]
