# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-06 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0026_auto_20200306_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='big_total',
        ),
    ]
