# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-06 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0029_auto_20200306_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='sub_total',
        ),
    ]
