# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-13 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerimage',
            name='name',
            field=models.CharField(default='', max_length=254),
        ),
    ]
