# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-28 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bannerimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerimage',
            name='description',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='bannerimage',
            name='tag',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='bannerimage',
            name='title',
            field=models.CharField(default='', max_length=254),
        ),
    ]
