# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-13 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200213_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='', max_length=254),
        ),
    ]
