# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-13 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200213_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='number',
            field=models.CharField(default='', max_length=254),
        ),
    ]
