# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-24 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0245_auto_20200224_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_four',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_one',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_three',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_two',
            field=models.ImageField(upload_to='images'),
        ),
    ]
