# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-01 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0245_auto_20200301_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
