# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-24 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0246_auto_20200224_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date created',
            field=models.DateTimeField(default=0),
        ),
    ]
