# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-24 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0248_auto_20200224_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(verbose_name='date created'),
        ),
    ]
