# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-24 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0251_remove_product_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(default='', verbose_name='date created'),
        ),
    ]
