# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-24 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0252_product_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_date',
        ),
    ]
