# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-24 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0254_product_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='number',
        ),
    ]
