# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-24 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0255_remove_categorie_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='description_line_one',
            field=models.CharField(default='', max_length=254),
        ),
    ]
