# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-29 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0257_auto_20200224_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name_overflow',
            field=models.CharField(default='', max_length=254),
        ),
    ]
